[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  # Disable Next.js plugin detection
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Explicitly disable framework detection
[framework]
  name = "static"

# Git-based deployment settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

# Redirect rules for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
